### PR TITLE
Fix Crosseling products with visibility set to nowhere

### PR DESCRIPTION
**Pull request by FabienPapet**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Type?         | bug fix
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes PrestaShop/Prestashop#24784
| How to test?  | See bug report

### CODE REVIEW

**Comment by FabienPapet** [comment]
Thank you for reviewing, I've updated the code with your suggestions.

**Review by kpodemski — APPROVED** [review]

**Review by matks — APPROVED** [review]

**Review by lmeyer1 — APPROVED** [review]
Thanks for this fix. It is an important one.

**Comment by hibatallahAouadni** [comment]
Hello @FabienPapet 

LGTM, QA :heavy_check_mark: 
Thanks!

**Review by matthieu-rolland — COMMENTED** [review]
thank you @FabienPapet and @hibatallahAouadni

**Comment by PrestaEdit** [comment]
Hi there,

For my culture, why don't you use the given syntax by @kpodemski with the `""`(used as this inside the core) instead of the `\'\'` ?

**Pull request merged**
